### ISSUE TITLE
Big Issue with 2.2.2

### ISSUE THREAD

**Issue by joecoolio66** [PrestaShop/ps_emailalerts#80]
We upgraded this afternoon and immediately noticed that 500 errors were happening in our shop.  Customers couldn't make orders... payment was coming in but orders were not created because 500 errors were generated at validation.  

We are using prestashop 1.7.5.2

We searched through our shop and realized it was causing issues with Symfony:

[2021-03-17 21:13:36] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\UndefinedMethodException: "Attempted to call an undefined method named "getLocale" of class "Language". Did you mean to call "getLocaleByIso"?" at /home2/canadac3/public_html/modules/ps_emailalerts/ps_emailalerts.php line 552 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\UndefinedMethodException(code: 0): Attempted to call an undefined method named \"getLocale\" of class \"Language\".\nDid you mean to call \"getLocaleByIso\"? at /home2/canadac3/public_html/modules/ps_emailalerts/ps_emailalerts.php:552)"} []
[2021-03-17 21:13:36] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []

We reverted back to 2.2.1 and the errors went away.

**Comment by sorin982** [comment]
Same situation after update.
The orders have been created, they have values but they are completely empty, without the ordered products, without the payment method, status, carrier....

2021-03-17 20:34:35.868376 [NOTICE] [8629] [86.123.106.86:60171-Q:259C35AF5F3CF221-47#APVH_www.*****:443] [STDERR] PHP Fatal error:  Uncaught Error: Call to undefined method Language::getLocale() in domains/****/public_html/modules/ps_emailalerts/ps_emailalerts.php:552
Stack trace:
#0 domains/****/public_html/classes/Hook.php(966): Ps_EmailAlerts->hookActionUpdateQuantity(Array)
PrestaShop/ps_emailalerts#1 domains/****/public_html/override/classes/Hook.php(50): HookCore::coreCallHook(Object(Ps_EmailAlerts), 'hookactionUpdat...', Array)
PrestaShop/ps_emailalerts#2 domains/****/public_html/classes/Hook.php(351): Hook::coreCallHook(Object(Ps_EmailAlerts), 'hookactionUpdat...', Array)
PrestaShop/ps_emailalerts#3 domains/****/public_html/classes/Hook.php(903): HookCore::callHookOn(Object(Ps_EmailAlerts), 'actionUpdateQua...', Array)
PrestaShop/ps_emailalerts#4 domains/****/public_html/src/Adapter/HookManager.php(80): HookCore::exec('actionUpdateQua...', Array, NULL, false, true, false, NULL)
PrestaShop/ps_emailalerts#5 domains/****/public_html/src/Core/Stock/StockManager.php(190): PrestaShop\PrestaShop\Adapter\HookM in domains/****/public_html/modules/ps_emailalerts/ps_emailalerts.php on line 552

**Comment by futurowebpl** [comment]
Fatal checkout blocking bug. This shouldn't have happened.

Shops below 1.7.6 appear to be affected,

Workaround = Downgrade module to version 2.1.

I can see that there have been changes to the translation system and older versions have not been taken into account,

the method Language :: getLocale () is used, this method does not exist in Prestashop below 1.7.6.

**Comment by xexu** [comment]
Can confirm this issue happening on 1.7.3.2 messing up new orders since it crashes during the execution of actionValidateOrder.

From what I've gathered the function Language::getLanguage is only available on branches [1.7.6.x](https://github.com/PrestaShop/PrestaShop/blob/1ae609dbd6f6575d1bd97494105c4c367ffa5224/classes/Language.php#L1493) and [1.7.7.x](https://github.com/PrestaShop/PrestaShop/blob/b0d831a1d32161c9c03a95e16cd5490f047839a0/classes/Language.php#L1596).

An easy workaround is to downgrade to version 2.2.1 of the module.

**Comment by matks** [comment]
Hi everyone, this bug is being investigated and a release will be provided soon as it is likely to prevent people from completing order
